Dz4 2 modal
js-tasks-ru/htmlcss-20230411_valentina-471094 pull request #11
Opened 2023-04-30 06:22 UTC by valentina-romats

2023-04-30 06:23 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-30 06:23 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-01 12:30 UTC, GSemikozov requested changes

2023-05-01 12:30 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  top: 50%;
по середине экрана будем размещать именно .modal__window (absolute | relative). А сам блок - растягиваем на всю страницу

2023-05-01 12:30 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  top: 50%;
и задаем лишь полупрозрачный фон через rgba

2023-05-01 19:49 UTC, valentina-romats commented on 05-lection3/02-modal/modal.css
> +  top: 50%;
Fixed

2023-05-02 14:49 UTC, GSemikozov approved these changes

2023-05-02 14:49 UTC, merged