dz-4-3-calendar
js-tasks-ru/htmlcss-20230411_valentina-471094 pull request #12
Opened 2023-05-01 07:53 UTC by valentina-romats

2023-05-01 07:54 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-01 12:30 UTC, GSemikozov requested changes

2023-05-01 12:30 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +  padding: 28px 30px;
`28 26 32`

2023-05-01 19:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-01 19:47 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-05-01 19:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-05-01 19:49 UTC, valentina-romats commented on 05-lection3/03-calendar/calendar.css
> +  padding: 28px 30px;
Fixed

2023-05-01 19:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-05-02 14:49 UTC, GSemikozov approved these changes

2023-05-02 14:49 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2023-05-02 14:50 UTC, GSemikozov approved these changes

2023-05-02 14:50 UTC, merged