dz4-4-page-template
js-tasks-ru/htmlcss-20230411_valentina-471094 pull request #13
Opened 2023-05-03 16:53 UTC by valentina-romats

2023-05-03 16:54 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-04 15:04 UTC, GSemikozov requested changes

2023-05-04 15:04 UTC, GSemikozov commented on pages/template.html
> +  <div class="page page__template">
page_template

2023-05-04 15:04 UTC, GSemikozov commented on pages/template.html
> +    <div class="page__header">
у нас уже есть блок header

2023-05-04 15:04 UTC, GSemikozov commented on pages/template.html
> +    <div class="page__context">
уже есть блок page. Класс page__context можно домиксовать при необходимости

2023-05-04 15:04 UTC, GSemikozov commented on pages/template.html
> +      <div class="container page__context_grid">
page__context_grid - модификатор элемента page__context, с ним и должен применяться

2023-05-04 15:04 UTC, GSemikozov commented on pages/template.html
> +          <div class="section">
section - слишком размытое имя для такого специфического контента) лучше реализовать как элементы menu например

2023-05-04 15:04 UTC, GSemikozov commented on pages/template.html
> +    <div class="page__footer">
такой блок уже есть

2023-05-04 16:26 UTC, valentina-romats commented on pages/template.html
> +    <div class="page__context">
не поняла(

2023-05-04 16:27 UTC, valentina-romats commented on pages/template.html
> +      <div class="container page__context_grid">
не поняла( как я тогда сделаю раскладку, чтоб внутри использовать блок container?

2023-05-08 20:07 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-05-11 13:53 UTC, GSemikozov approved these changes

2023-05-11 13:54 UTC, merged