dz3-2-accordion
js-tasks-ru/htmlcss-20230411_valentina-471094 pull request #6
Opened 2023-04-23 21:57 UTC by valentina-romats

2023-04-23 21:58 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-24 19:43 UTC, GSemikozov requested changes

2023-04-24 19:43 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__item {
при .accordion__item[open] - padding-bottom: 32px

2023-04-24 19:55 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-24 20:49 UTC, GSemikozov approved these changes

2023-04-24 20:49 UTC, merged